EnableReaction(CREATEPROCESSA+)
EnableReaction(CREATEPROCESSW+)
EnableReaction(CREATETHREAD+)
EnableReaction(CREATEREMOTETHREAD+)
EnableReaction(OPENPROCESS+)
EnableReaction(SETTHREADCONTEXT+)
EnableReaction(RESUMETHREAD+)
